const C=[['ones','Ones'],['twos','Twos'],['threes','Threes'],['fours','Fours'],['fives','Fives'],['sixes','Sixes'],['threeKind','Three of a Kind'],['fourKind','Four of a Kind'],['fullHouse','Full House'],['smallStraight','Small Straight'],['largeStraight','Large Straight'],['yahtzyy','yahtzyy'],['chance','Chance']];
const KEY='yahtzyy-pwa-v4';
const player=n=>({name:n,scores:{}}); const fresh=()=>({players:[player('Player 1')],active:0,round:0,dice:[1,1,1,1,1],held:[false,false,false,false,false],rolls:0,mode:null,manual:false});
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}})(); if(!state.players?.length)state=fresh();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)); const sum=()=>state.dice.reduce((a,b)=>a+b,0); const counts=()=>state.dice.reduce((a,n)=>(a[n]=(a[n]||0)+1,a),{});
function straight(n){let u=[...new Set(state.dice)].sort((a,b)=>a-b),r=1;for(let i=1;i<u.length;i++){r=u[i]===u[i-1]+1?r+1:1;if(r>=n)return true}return false}
function pot(k){let c=counts(),v=Object.values(c),s=sum();if(/^ones|twos|threes|fours|fives|sixes$/.test(k)){let n={ones:1,twos:2,threes:3,fours:4,fives:5,sixes:6}[k];return state.dice.filter(x=>x===n).length*n}if(k==='threeKind')return v.some(x=>x>=3)?s:0;if(k==='fourKind')return v.some(x=>x>=4)?s:0;if(k==='fullHouse')return v.includes(3)&&v.includes(2)?25:0;if(k==='smallStraight')return straight(4)?30:0;if(k==='largeStraight')return straight(5)?40:0;if(k==='yahtzyy')return v.includes(5)?50:0;return s}
function upper(p){return C.slice(0,6).reduce((a,[k])=>a+(p.scores[k]??0),0)} function total(p){return Object.values(p.scores).reduce((a,b)=>a+b,0)+(upper(p)>=63?35:0)} function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(x){let t=document.querySelector('#toast');t.textContent=x;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),1500)}
function mode(m){state.mode=m;state.rolls=0;state.held.fill(false);save();render();toast(m==='virtual'?'Virtual dice selected':'Physical dice selected — use Edit Scores to record your rolls')}
function dice(){let card=document.querySelector('#diceCard');if(!state.mode){card.classList.add('hidden');return}card.classList.remove('hidden');document.querySelector('#diceTitle').textContent=state.mode==='virtual'?'Virtual Dice':'Physical Dice';document.querySelector('#rollLabel').textContent=state.mode==='virtual'?`Roll ${state.rolls} / 3`:'Roll your physical dice';document.querySelector('#diceHint').textContent=state.mode==='virtual'?'Tap a die to hold it between rolls.':'Use your physical dice, then click Edit Scores to enter the score you actually earned.';document.querySelector('#rollBtn').classList.toggle('hidden',state.mode!=='virtual');document.querySelector('#clearHoldsBtn').classList.toggle('hidden',state.mode!=='virtual');let e=document.querySelector('#dice');e.innerHTML='';if(state.mode==='physical'){e.innerHTML='<span class="hint">Physical dice mode is active. No virtual roll is required.</span>'}else state.dice.forEach((n,i)=>{let b=document.createElement('button');b.className='die'+(state.held[i]?' held':'');b.textContent=n;b.onclick=()=>{if(state.rolls){state.held[i]=!state.held[i];save();dice()}};e.appendChild(b)});document.querySelector('#rollBtn').disabled=state.rolls>=3||state.round>=13}
function players(){let e=document.querySelector('#players');e.innerHTML='';state.players.forEach((p,i)=>{let d=document.createElement('div');d.className='player '+(i===state.active?'active':'');let inp=document.createElement('input');inp.value=p.name;inp.onchange=()=>{p.name=inp.value.trim()||`Player ${i+1}`;save();render()};d.appendChild(inp);if(state.players.length>1){let x=document.createElement('button');x.className='remove';x.textContent='×';x.onclick=()=>{state.players.splice(i,1);state.active=Math.min(state.active,state.players.length-1);save();render()};d.appendChild(x)}d.onclick=e=>{if(e.target!==inp&&e.target.tagName!=='BUTTON'){state.active=i;save();render()}};e.appendChild(d)})}
function scorecard(){let w=document.querySelector('#scoreTableWrap'),t=document.createElement('table');t.className='score-table';let h='<thead><tr><th>Category</th>'+state.players.map(p=>`<th>${esc(p.name)}</th>`).join('')+'</tr></thead><tbody><tr class="subhead"><td colspan="'+(state.players.length+1)+'">Upper Section</td></tr>';for(let x of C.slice(0,6))h+=row(x);h+='<tr class="total"><td>Upper Total</td>'+state.players.map(p=>`<td>${upper(p)}</td>`).join('')+'</tr><tr class="total"><td>Bonus (63+)</td>'+state.players.map(p=>`<td>${upper(p)>=63?35:0}</td>`).join('')+'</tr><tr class="subhead"><td colspan="'+(state.players.length+1)+'">Lower Section</td></tr>';for(let x of C.slice(6))h+=row(x);h+='<tr class="total"><td>Grand Total</td>'+state.players.map(p=>`<td>${total(p)}</td>`).join('')+'</tr></tbody>';t.innerHTML=h;w.innerHTML='';let s=document.createElement('div');s.className='score-wrap';s.appendChild(t);w.appendChild(s);
function row([k,n]){return `<tr><td class="category">${n}</td>`+state.players.map((p,i)=>{let v=p.scores[k];if(state.manual)return `<td class="score-cell manual-cell"><input class="score-input" type="number" min="0" step="1" value="${v??''}" data-p="${i}" data-k="${k}"></td>`;if(v!==undefined)return `<td class="score-cell scored">${v}</td>`;let can=i===state.active&&(state.mode==='physical'||state.rolls>0);return `<td class="score-cell ${can?'available':''}" data-p="${i}" data-k="${k}">${can?(state.mode==='virtual'?pot(k):'Enter'):'—'}</td>`}).join('')+'</tr>'}
t.querySelectorAll('.available').forEach(x=>x.onclick=()=>record(+x.dataset.p,x.dataset.k));t.querySelectorAll('.score-input').forEach(x=>x.onchange=()=>{let p=state.players[+x.dataset.p],k=x.dataset.k;if(x.value.trim()==='')delete p.scores[k];else p.scores[k]=Math.max(0,Math.floor(Number(x.value)||0));save();render()})}
function record(i,k){if(i!==state.active||state.players[i].scores[k]!==undefined)return;state.players[i].scores[k]=state.mode==='virtual'?pot(k):0;state.round++;state.active=(state.active+1)%state.players.length;state.dice=[1,1,1,1,1];state.held.fill(false);state.rolls=0;save();render();toast('Score recorded')}
function roll(){if(state.mode!=='virtual'||state.rolls>=3)return;state.dice=state.dice.map((v,i)=>state.held[i]?v:Math.floor(Math.random()*6)+1);state.rolls++;save();render()}
function render(){document.querySelector('#roundLabel').textContent=state.round>=13?'Game Complete':state.mode?`Round ${Math.min(state.round+1,13)} of 13`:'Choose a dice mode';document.querySelector('#modeCard').classList.toggle('hidden',!!state.mode);document.querySelector('#scoreHint').textContent=state.manual?'Manual editing enabled':'Automatic scoring';dice();players();scorecard()}
document.querySelector('#virtualModeBtn').onclick=()=>mode('virtual');document.querySelector('#physicalModeBtn').onclick=()=>mode('physical');document.querySelector('#changeModeBtn').onclick=()=>{state.mode=null;state.rolls=0;state.held.fill(false);save();render()};document.querySelector('#rollBtn').onclick=roll;document.querySelector('#clearHoldsBtn').onclick=()=>{state.held.fill(false);save();dice()};document.querySelector('#addPlayerBtn').onclick=()=>{state.players.push(player(`Player ${state.players.length+1}`));save();render()};document.querySelector('#manualScoreBtn').onclick=()=>{state.manual=!state.manual;save();render();toast(state.manual?'Manual score editing enabled':'Manual score editing disabled')};document.querySelector('#newGameBtn').onclick=()=>{if(confirm('Start a new game? Current scores will be erased.')){state=fresh();save();render()}};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
